//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NguyenThiPhuongUyen_2001170230_doAn.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMINN
    {
        public string TENDN { get; set; }
        public string HOTEN { get; set; }
        public string MATKHAU { get; set; }
    }
}
