//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NguyenThiPhuongUyen_2001170230_doAn.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BINHLUAN
    {
        public int MABL { get; set; }
        public Nullable<int> MATIN { get; set; }
        public string TAIKHOAN { get; set; }
        public string NOIDUNG { get; set; }
        public Nullable<System.DateTime> DATEBL { get; set; }
    
        public virtual TIN TIN { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
    }
}
