//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NguyenThiPhuongUyen_2001170230_doAn.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLBANMYPHAMEntities : DbContext
    {
        public QLBANMYPHAMEntities()
            : base("name=QLBANMYPHAMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ADMINN> ADMINNs { get; set; }
        public DbSet<BINHLUAN> BINHLUANs { get; set; }
        public DbSet<CHITIETDH> CHITIETDHs { get; set; }
        public DbSet<DONHANG> DONHANGs { get; set; }
        public DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public DbSet<SANPHAM> SANPHAMs { get; set; }
        public DbSet<THELOAI> THELOAIs { get; set; }
        public DbSet<THUONGHIEU> THUONGHIEUx { get; set; }
        public DbSet<TIN> TINs { get; set; }
    }
}
