//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NguyenThiPhuongUyen_2001170230_doAn.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DONHANG
    {
        public DONHANG()
        {
            this.CHITIETDHs = new HashSet<CHITIETDH>();
        }
    
        public string MADH { get; set; }
        public string TAIKHOAN { get; set; }
        public string TINHTRANGTHANHTOAN { get; set; }
        public string TINHTRANGGIAOHANG { get; set; }
        public Nullable<System.DateTime> NGAYDAT { get; set; }
        public Nullable<System.DateTime> NGAYGIAO { get; set; }
    
        public virtual ICollection<CHITIETDH> CHITIETDHs { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
    }
}
