//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NguyenThiPhuongUyen_2001170230_doAn.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHACHHANG
    {
        public KHACHHANG()
        {
            this.BINHLUANs = new HashSet<BINHLUAN>();
            this.DONHANGs = new HashSet<DONHANG>();
        }
    
        public string HOTEN { get; set; }
        public string DIACHI { get; set; }
        public string TAIKHOAN { get; set; }
        public string PASS { get; set; }
        public string SDT { get; set; }
    
        public virtual ICollection<BINHLUAN> BINHLUANs { get; set; }
        public virtual ICollection<DONHANG> DONHANGs { get; set; }
    }
}
