//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NguyenThiPhuongUyen_2001170230_doAn.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        public SANPHAM()
        {
            this.CHITIETDHs = new HashSet<CHITIETDH>();
        }
    
        public string MASP { get; set; }
        public string TENSP { get; set; }
        public string MATL { get; set; }
        public string PHOTO { get; set; }
        public string MATH { get; set; }
        public string MOTA { get; set; }
        public Nullable<decimal> GIA { get; set; }
        public Nullable<System.DateTime> NGAYCAPNHAT { get; set; }
        public Nullable<int> SOLUONGTON { get; set; }
    
        public virtual ICollection<CHITIETDH> CHITIETDHs { get; set; }
        public virtual THUONGHIEU THUONGHIEU { get; set; }
        public virtual THELOAI THELOAI { get; set; }
    }
}
